-- 자유게시판 : 테이블 2개 (메인글저장, 댓글저장)

CREATE TABLE FREEBOARD(
	IDX int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,						-- 작성자
	PASSWORD VARCHAR(10) NOT NULL,					-- 글 비밀번호
	SUBJECT VARCHAR(40) NOT NULL,					-- 글 제목
	CONTENT VARCHAR(2000) NOT NULL,					-- 내용
	READCOUNT INT DEFAULT 0,						-- 조회수
	WDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,		-- 서버의 현재 날짜/시간
	IP VARCHAR(15) DEFAULT '127.0.0.1',				-- 접속자 IP
	COMMENTCOUNT SMALLINT DEFAULT 0,				-- 댓글 갯수
	PRIMARY KEY(IDX)
);

INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('honey','1111','웰컴 ~~','하이 반가워','192,168,17,3');
INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('사나','1111','welcome my home ~~','하이 반가워 어서와','192.168.22.3');
INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('나나','1111','굿바이 ~~','잘가 또봐','19.168.23.3');
INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('nayeon','1111','웰컴 ~~','하이 반가워2','192.168.24.3');
INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('박찬호','1111','헬로우~~','운동좀 하자','192.168.25.4');
INSERT INTO FREEBOARD (NAME, PASSWORD, SUBJECT, CONTENT,IP)
VALUES('세리박','1111','하이 ~~','운동하러 가야지','192.168.26.7');

SELECT * FROM FREEBOARD;

-- mysql limit 키워드 : limit 번호, 갯수
-- mysql, oracle select 결과에 대해 각행에 순서대로 번호를 부여하는 컬럼이 만들어짐
SELECT * FROM FREEBOARD ORDER BY IDX DESC;
SELECT * FROM FREEBOARD ORDER BY IDX DESC LIMIT 0, 15;	-- 1 페이지
SELECT * FROM FREEBOARD ORDER BY IDX DESC LIMIT 15, 15;	-- 2 페이지
SELECT * FROM FREEBOARD ORDER BY IDX DESC LIMIT 30, 15;	-- 3 페이지
-- 계산식 : n=10 페이지 글? (n-1)*15
SELECT * FROM FREEBOARD ORDER BY IDX DESC LIMIT 135, 15;	-- 10 페이지
COMMIT;
-- 글 수정 : subject, content 수정. idx 컬럼을 조건
UPDATE freeboard SET subject = '굿나잇~', content='잘자고 내일보자' WHERE idx=154;

-- 조회수 변경 : 읽을 때마다(url 요청 발생) count + 1
UPDATE freeboard SET READCOUNT = READCOUNT + 1 WHERE idx = 154;

-- 글 삭제 : 글 비밀번호 1) 있을 떄 2) 없을 때
DELETE FROM FREEBOARD WHERE IDX=151 AND PASSWORD ='0000';
DELETE FROM FREEBOARD WHERE IDX=151 AND PASSWORD IS NULL;
